### PR TITLE
added typedef for casting callback fnc without optional pointer

### PR DESCRIPTION
**Pull request by Chipable**
Contains a working adc.c and .h. Was pulled after Nikola's pull request was approved.

### CODE REVIEW

**Review by muhlbaier — COMMENTED** [review]
Is there any reasonable example where the user of the adc module would need callback_no_input_t? (i.e. not in adc.c)

**Comment by Chipable** [comment]
There is no change to the end user interface with the adc module. The typedef just provides more readable code in adc.c

**Comment by muhlbaier** [comment]
Since the typedef isn't for the user of the module it should go in adc.c. To be a sufficient contribution you could add a typedef and an example in adc.h for this type of function pointer:
void (*)(uint16_t, void*)
This way the user of the module could use this to cast functions that don't match that when they pass them into ADC_AddChannel()

**Comment by Chipable** [comment]
Requested changes have been implemented.

**Review by muhlbaier — CHANGES_REQUESTED** [review]
Good but update the example. It would be dangerous for someone to use the void * to pass to a uint8_t and could corrupt the stack. The more likely and intended example would be when the callback doesn't have the pointer input:
void callback (uint16_t value);

**Comment by Chipable** [comment]
Comments Incorporated with the addition of fixing callback_input_t by adding '*'

**Review by muhlbaier — APPROVED** [review]
Looks good.

**Pull request merged**
